<?php
/**
 * Plugin Name: ryangoldbacher Site
 * Description: Site-specific plugin for ryangoldbacher, generated by to-wordpress. Placeholder until the Plugin phase completes.
 * Version: 0.1.0
 * License: GPL-2.0-or-later
 * Text Domain: ryangoldbacher-site
 */
if (!defined('ABSPATH')) { exit; }
